# Generated by Django 4.2.6 on 2023-10-16 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDeskUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_desk_name', models.CharField(max_length=100)),
                ('service_desk_email', models.EmailField(max_length=254)),
                ('service_desk_phone', models.CharField(max_length=10)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.userprofile')),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_Email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Contact_Number',
            new_name='customer_phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_saleuser',
            new_name='is_sales_login',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Company_Name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Customer_Name',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_location',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_service_desk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_technician',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TechnicianLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_name', models.CharField(max_length=100)),
                ('technician_email', models.EmailField(max_length=254)),
                ('technician_phone', models.CharField(max_length=10)),
                ('service_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.servicedeskuser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='servicedeskuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
