# Generated by Django 4.2.6 on 2023-10-18 03:59

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_servicedeskuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=mainapp.models.get_current_date),
        ),
    ]
