# Generated by Django 4.2.6 on 2023-10-18 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_created_at_customer_customer_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_created_at',
            new_name='created_at',
        ),
    ]
