# Generated by Django 4.2.6 on 2023-10-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_customer_created_at_customer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(default='Company', max_length=100),
        ),
    ]
