# Generated by Django 4.2.6 on 2023-10-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_technicianlogin_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=1000)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=10)),
                ('service_status', models.CharField(choices=[('Created', 'Accepted'), ('Closed', 'Closed')], max_length=20)),
                ('Technician_service_status', models.CharField(choices=[('Accepted', 'Accepted'), ('In-progress', 'In-progress'), ('Closed', 'Closed')], max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.products')),
            ],
        ),
    ]
